### ISSUE TITLE
Docker Composeファイルに関する1つの提案

### ISSUE THREAD

**Issue by KooriMoe** [datsukan/outlinewiki-docker-compose#3]
まず、Outline Wikiの展開を容易にするためにComposeを提供していただきありがとうございます。
First of all, thank you for providing Compose to facilitate the deployment of Outline Wiki.

しかし、私は個人的にPostgresとRedisコンテナを作成することについて提案があります。
But I personally have a suggestion about creating Postgres and Redis containers.

私の提案は、コンテナがホストのポートを占有しないようにすることです。 コンテナ名でOutlineWikiコンテナをPostgresおよびRedisコンテナに直接接続します。
My suggestion is to not let the container occupy the host's port. Directly let the Outline Wiki container connect to Postgres and Redis containers by container name.

これがdocker-composeの例です。
Here is an example of docker-compose.

```
version: "3"

services:

  outline:
    container_name: outline-outline
    image: outlinewiki/outline:0.61.1
    command: sh -c "yarn db:migrate --env production-ssl-disabled && yarn start"
    env_file: ./.env
    hostname: localhost
    ports:
      - "3000:3000"
    networks:
      - common

  postgres:
    container_name: outline-postgres
    image: postgres:13.2
    hostname: localhost
    environment:
      - TZ
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_INITDB_ARGS
    networks:
      - common
    volumes:
      - outline-postgres-data:/var/lib/postgresql/data

  redis:
    container_name: outline-redis
    image: "redis:latest"
    networks:
      - common
    volumes:
      - outline-redis-data:/data

volumes:
  outline-postgres-data:
    driver: local
  outline-redis-data:
    driver: local

networks:
  common:
    driver: bridge
```

この構成は通常どおりに使用でき、ホストのポートを占有しません。
This configuration can be used normally and will not occupy the host's port.
